MVC/Models/Driver.cs
using Microsoft.AspNetCore.Identity;

namespace BusManagementSystem.Models;

public class Driver : IdentityUser
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public bool IsManager { get; set; }
    public bool IsActive { get; set; }
    
    public ICollection<Entry> Entries { get; }
}

MVC/ViewModels/EntryCreatorViewModel.cs
using BusManagementSystem.Models;

namespace BusManagementSystem.ViewModels;

public class EntryCreatorViewModel
{
    public Bus Bus { get; set; }
    public Loop Loop { get; set; }
    public Entry Entry { get; set; } = new Entry();
    public int SelectedStopId { get; set; }
    public int BusId { get; set; }
    public int LoopId { get; set; }
    public string DriverId { get; set; }
}

MVC/Controllers/DriverController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BusManagementSystem.Service;
using BusManagementSystem.ViewModels;
using BusManagementSystem.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;

namespace BusManagementSystem.Controllers;

[Authorize]
public class DriverController : Controller
{
    private readonly ILoopServiceInterface _loopServiceInterface;
    private readonly IRouteServiceInterface _routeServiceInterface;
    private readonly IBusServiceInterface _busServiceInterface;

    private readonly UserManager<Driver> _userManager;
    private readonly SignInManager<Driver> _signInManager;
    private readonly ILogger<DriverController> _logger;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public DriverController(ILoopServiceInterface loopServiceInterface, IRouteServiceInterface routeServiceInterface,
        IBusServiceInterface busServiceInterface,
        UserManager<Driver> userManager, SignInManager<Driver> signInManager, ILogger<DriverController> logger,
        IHttpContextAccessor httpContextAccessor)
    {
        _loopServiceInterface = loopServiceInterface;
        _routeServiceInterface = routeServiceInterface;
        _busServiceInterface = busServiceInterface;
        _userManager = userManager;
        _signInManager = signInManager;
        _logger = logger;
        _httpContextAccessor = httpContextAccessor;
    }

    public async Task<IActionResult> SelectBusLoop()
    {
        ViewData["BusId"] = new SelectList(_busServiceInterface.GetBuses(), "Id", "BusNumber");
        ViewData["LoopId"] = new SelectList(_loopServiceInterface.GetLoops(), "Id", "Name");
        ViewData["IsActive"] = User.HasClaim("IsActive", "true");
        return View();
    }

    [HttpPost]
    [Authorize(Policy = "ActiveOnly")]
    public async Task<IActionResult> StartDriving(int BusId, int LoopId)
    {
        Bus selectedBus = await _busServiceInterface.GetBus(BusId);
        Loop selectedLoop = await _loopServiceInterface.GetLoop(LoopId);
        _logger.LogInformation("Bus id {id} started driving on loop {loop} at {time}", BusId, selectedLoop.Name,
            DateTime.Now);
        return RedirectToAction("EntryCreator", new { BusId = selectedBus.Id, LoopId = selectedLoop.Id });
    }


    [Authorize(Policy = "ActiveOnly")]
    public async Task<IActionResult> EntryCreator(int BusId, int LoopId)
    {
        Bus selectedBus = await _busServiceInterface.GetBus(BusId);
        Loop selectedLoop = await _loopServiceInterface.GetLoop(LoopId);
        _routeServiceInterface.GetRoutes();

        EntryCreatorViewModel entryCreatorViewModel = new EntryCreatorViewModel
        {
            Bus = selectedBus,
            Loop = selectedLoop,
            Entry = new Entry(),
            BusId = BusId,
            LoopId = LoopId,
        };

        return View(entryCreatorViewModel);
    }

    [Authorize(Policy = "ManagerOnly")]
    public async Task<IActionResult> ApproveDriver(string userId)
    {
        _logger.LogInformation("Approve Driver called for user {id} at {time}.", userId, DateTime.Now);
        var user = await _userManager.FindByIdAsync(userId);
        if (user == null)
        {
            _logger.LogWarning("Approve Driver called on user that does not exist.", DateTime.Now);
            return NotFound();
        }

        var claim = new Claim("IsActive", "true");
        var result = await _userManager.AddClaimAsync(user, claim);

        if (!result.Succeeded)
        {
            _logger.LogError("Failed to add IsActive claim to user.");
            return BadRequest();
        }

        user.IsActive = true;
        await _userManager.UpdateAsync(user);
        
        _logger.LogInformation("User with id {userId} approved at {time}.", userId, DateTime.Now);

        return RedirectToAction("Dashboard", "Home");
    }
}

MVC/Views/Driver/EntryCreator.cshtml
@using System.Text.Json
@using BusManagementSystem.Service
@inject IRouteServiceInterface _routeServiceInterface
@inject IStopServiceInterface _stopServiceInterface
@model BusManagementSystem.ViewModels.EntryCreatorViewModel

@{
    ViewData["Title"] = "Trip Log";
    <link rel="stylesheet" href="~/css/entry_creator.css"/>
    var routes = _routeServiceInterface.GetRoutesWithLoopId(Model.Loop.Id);
}

<div id="entry-creator-container">
    <div id="entry-creator-header">
        <h1>Trip Log</h1>
        <div id="trip-info">
            <span>Driving on <strong>@Html.Raw(Model.Loop.Name)</strong>.</span>
            <span>Bus #<strong>@Html.Raw(Model.Bus.BusNumber)</strong>.</span>
        </div>
    </div>
    <hr id="separator">
    <div id="entry-creator-form-container">
        <form id="entry-creator-form" asp-controller="Entry" asp-action="Create" method="post">
            <div id="form-section">
                <label class="form-label" for="SelectedStopId">Stop:</label>
                <select id="selected-stop-id" asp-for="SelectedStopId">
                    @foreach (var route in routes)
                    {
                        var stop = await _stopServiceInterface.GetStop(route.StopId);
                        <option value=@route.StopId>@stop.Name</option>
                    }
                </select>
            </div>
            <div id="form-section">
                <label class="form-label" asp-for="Entry.Boarded">Passengers boarded:</label>
                <input type="text" placeholder="Enter..." asp-for="Entry.Boarded" class="form-control"/>
            </div>
            <div id="form-section">
                <label class="form-label" asp-for="Entry.LeftBehind">Passengers left behind:</label>
                <input type="text" placeholder="Enter..." asp-for="Entry.LeftBehind" class="form-control"/>
            </div>
            <input type="hidden" asp-for="BusId"/>
            <input type="hidden" asp-for="DriverId">
            <input type="hidden" asp-for="LoopId"/>
            <input type="hidden" asp-for="Entry.Bus.Id" value="@Model.BusId"/>
            <input type="hidden" asp-for="Entry.Loop.Id" value="@Model.LoopId"/>
            <input type="hidden" asp-for="Entry.Stop.Id" value="@Model.SelectedStopId"/>
            <div>
                <input type="submit" class="btn btn-primary" id="entry-creator-button" value="Next Stop"/>
                <a type="submit" class="btn btn-danger" id="end-trip-button" asp-controller="Driver" asp-action="SelectBusLoop">End Trip</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        document.getElementById("entry-creator-form").addEventListener("submit", function (event) {
            event.preventDefault();
    
            const formData = new FormData(event.target);
            console.log("Entry form data: ", formData);
    
            fetch(event.target.action, {
                method: 'POST',
                body: formData
            })
            .then(response => {
                if (response.ok) {
                    const stopIdSelect = document.getElementById("selected-stop-id");
                    const nextStopIndex = stopIdSelect.selectedIndex + 1;
    
                    if (nextStopIndex < stopIdSelect.options.length) {
                        stopIdSelect.selectedIndex = nextStopIndex;
                    } else {
                        alert("You have reached the end of the loop. Please start a new trip or end the current trip.");
                    }
    
                    document.querySelector("input[name='Entry.Boarded']").value = "";
                    document.querySelector("input[name='Entry.LeftBehind']").value = "";
                } else {
                    console.log('Error:', response.statusText);
                }
            })
            .catch(error => {
                console.error('Error:', error);
            });
        });
    </script>
}

MVC/Views/Driver/SelectBusLoop.cshtml
@{
    ViewData["Title"] = "Select Bus and Loop";
    SelectList busSelectList = ViewBag.BusId as SelectList;
    SelectList loopSelectList = ViewBag.LoopId as SelectList;
    bool isActive = ViewBag.IsActive;
    <link rel="stylesheet" href="~/css/select_bus_loop.css" />
}

<div id="bus-loop-select-container">
    <div id="bus-loop-select-header">
        <h1>Select Bus and Loop</h1>
        <div id="buttons">
        </div>
    </div>
    <hr id="separator">
    <div id="form-container">
        @if (isActive)
        {
            <form id="bus-loop-select-form" asp-controller="Driver" asp-action="StartDriving" method="post">
                <div>
                    <label class="form-label" for="BusId">Bus Number:</label>
                    <select name="BusId" id="BusId" asp-items="busSelectList"></select>
                </div>
                <div>
                    <label class="form-label" for="LoopId">Loop:</label>
                    <select name="LoopId" id="LoopId" asp-items="loopSelectList"></select>
                </div>
                <div>
                    <input type="submit" class="btn btn-primary" id="bus-loop-select-button" value="Start Driving" />
                </div>
            </form>
        }
        else
        {
            <div class="alert alert-warning" role="alert">
                You are not yet activated or need to sign out and sign back in to access this feature.
            </div>
        }
    </div>
</div>